/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class school_calculator_SmartCalc_model_SmartCalcModelJNI */

#ifndef _Included_school_calculator_SmartCalc_model_SmartCalcModelJNI
#define _Included_school_calculator_SmartCalc_model_SmartCalcModelJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     school_calculator_SmartCalc_model_SmartCalcModelJNI
 * Method:    GetCalcResult
 * Signature: (Ljava/lang/String;)D
 */
JNIEXPORT jdouble JNICALL Java_school_calculator_SmartCalc_model_SmartCalcModelJNI_GetCalcResult
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
